POST http://localhost:3000/cidade
Content-Type: application/json

{
  "nome": "sao paulo",
  "estado": "sao paulo"
}
###

GET http://localhost:3000/cidade
###

GET http://localhost:3000/cidade/id
###

PUT http://localhost:3000/cidade/id
Content-Type: application/json

{
  "nome": "bh",
  "estado": "Minas Gerais"
}
###

DELETE http://localhost:3000/cidade/id
###