### Criar um Uf
POST http://localhost:3000/uf
Content-Type: application/json

{
  "nome": "",
  "descricao": "",
  "ativo": true
}

### Listar Ufs
GET http://localhost:3000/uf

### Buscar Uf por ID
GET http://localhost:3000/uf/id

### Atualizar Uf
PUT http://localhost:3000/uf/id
Content-Type: application/json

{
  "nome": "",
  "descricao": "",
  "ativo": true
}

### Remover Uf
DELETE http://localhost:3000/uf/id
