### Criar um Estudante
POST http://localhost:3000/estudante
Content-Type: application/json

{
  "nome": "",
  "descricao": "",
  "ativo": true
}

### Listar Estudantes
GET http://localhost:3000/estudante

### Buscar Estudante por ID
GET http://localhost:3000/estudante/id

### Atualizar Estudante
PUT http://localhost:3000/estudante/id
Content-Type: application/json

{
  "nome": "",
  "descricao": "",
  "ativo": true
}

### Remover Estudante
DELETE http://localhost:3000/estudante/id
